### ISSUE TITLE
[Design]: homepage GitHub button haven't good deep meaning

### ISSUE THREAD

**Issue by AugustinMauroy** [valkey-io/valkey-io.github.io#10]
# Context
If you go on actual deployment you see a button "Valkey source on GitHub".

<img width="1552" alt="Capture d’écran 2024-04-04 à 19 17 20" src="https://github.com/valkey-io/valkey-website/assets/97875033/91beddde-a1b1-4d48-befe-102e78ccdafc">

## Issue 

The issue is the deep-meaning of this button is download. 

Because in the majority of websites that deal with software projects. The big coloured buttons are for downloading.

**Comment by stockholmux** [comment]
@AugustinMauroy What you're seeing right now is really just stuff pulled from the template, far from a final product.

But yeah, very true. That button should go elsewhere.  Although the way valkey is consumed 'downloading' is probably not the right action. People will consume valkey in the following ways (in order of likely popularity):

- Container
- Package Manager
- Build from source
- Binary from release

That said the button should probably lead to some sort "Get Valkey" page with all of those options.

Do you want to take a stab at it?

**Comment by AugustinMauroy** [comment]
Honestly, I'm a JS dev. So I don't have the tools kit to run the project on my machine, but I'd be happy to help review it (don't hesitate to ping me).

**Comment by stockholmux** [comment]
closed by #47
