### ISSUE TITLE
[BUG] RSS feed has been accidentally removed

### ISSUE THREAD

**Issue by brainwo** [valkey-io/valkey-io.github.io#103]
**Describe the bug**
Currently https://valkey.io/atom.xml points to 404 File Not Found.

It seems like the recent commit https://github.com/valkey-io/valkey-io.github.io/commit/0ab9347c345327f58e5b22cdeb23f97928d38433 disables the generation of `atom.xml` file [2] and can be mitigated with one of options in [3].

```diff
- generate_feed = true
+ generate_feeds = true
```

**To Reproduce**
Not applicable

**Expected behavior**
`atom.xml` should present or RSS header [1] should point to valid url.

**Screenshots**
Not applicable

**Additional context**
[1] RSS header in the HTML file
```html
<link rel="alternate" type="application/atom+xml" title="Atom feed" href="https://valkey.io/atom.xml">
```

[2] Potential problem
From what I've seen and what I have been tried previously, this is likely has to do with the Zola version. Version of Zola being used in `.github/workflows/zola-deploy.yml` currently is `v0.18.0`. `generated_feeds` seems to be a breaking change for `generated_feed`, as previously I have been trying running this site on `v.0.19.1` with no success and had to downgrade to `v0.18.0` in my local development environment.

[3] Potential solution
Either bump the GitHub Action version of `zola-deploy.yml` or change the property name back to `generated_feed`.

**Comment by madolson** [comment]
Let me check on this now.

**Comment by madolson** [comment]
This should hopefully be fixed, I'm pushing this to production now.

**Comment by jfg956** [comment]
I confirm it is fixed.  The posts I reported as not reaching [Planet for the Valkey Community](https://valkey-demo.oursqlcommunity.org/) have reached the aggregator.

Thanks Madelyn.
