### ISSUE TITLE
[BUG] Replace dummy blog post

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-io.github.io#12]
**Describe the bug**

Current [dummy blog post](https://d18m7x5q574jh8.cloudfront.net/blog/update/2021/04/journey/) is weird and references 2021. This should be removed.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mjh316** [comment]
Delete or simply update the date?

**Comment by stockholmux** [comment]
@mjh316 I would delete it then have a real post about Valkey be the first post. That's a standard post from Jekyll when you init a site.
