### ISSUE TITLE
new static site generator

### ISSUE THREAD

**Issue by danish-mehmood** [valkey-io/valkey-io.github.io#120]
does this project intend to use the same SSG (zola) or does it intend to move towards a better option like Hugo. what is the future plan?

**Comment by madolson** [comment]
I think the answer is that Hugo is much more popular that Zola, so more people might be able to help and improve it.

**Comment by danish-mehmood** [comment]
i think @madolson has summed it up @zuiderkwast very well.
you are right that people will argue that zola is better than hugo but same way hugo would have its own proponents. Thats a never ending cycle in our industry.
the selling point for any SSG is how fast is it to convert a page to HTML and thats fairly consistent across all SSGs so performance should not be a deciding factor (in case of choosing an SSG).
a better factor to consider would be low barrier to entry and better ecosystem and an SSG like HUGO is miles ahead in that regard
P.S if c and go gave same performance no one would have written valkey in c language , same is the story of zola vs hugo

**Comment by zuiderkwast** [comment]
> low barrier to entry and better ecosystem and an SSG like HUGO is miles ahead in that regard

This doesn't say anything. What fo you wabt an ecosystem for? Running zola from a binary, no dependecies, seemed like zero entry barrier to me.

If you don't mention anything specific that hugo can do that zola can't, changing doesn't solve any real issue, then we can close this.

**Comment by danish-mehmood** [comment]
@zuiderkwast i am sure it was easy for you but every opensource contributor is not as experienced as you , projects like this should be very easy to contribute to for the new comers to the opensource

**Comment by zuiderkwast** [comment]
I don't know what you're referring to. I'm talking about running zola locally. That's all. I haven't used zola much other than that. I expect running hugo locally to preview pages is exactly the same. You would need to have hugo and you would have to run a command.

Or are you talking about writing logic, templates, etc. in zola vs hugo? I haven't done that in zola nor in hugo so I don't know the differences. This is where I want you to be specific about.

Writing content (I imagine) shouldn't require any of that, just plain markdown, but I may be wrong. What I would have liked is to be able to run things like python scripts to generate or preprocess content, but from what I've been told, that's against the spirit of a SSG.

**Comment by stockholmux** [comment]
@danish-mehmood The project just moved to Zola a few months ago from the initial Jekyll version. 

When it became clear that Jekyll didn't have a viable path forward for the site many people brought up opinions on SSGs. 
Several options were evaluated (Hugo was one of them; I personally have deep experience with Hugo as well) and Zola was settled on for variety of reasons, both project and technical. Moving to Hugo would be 100s of hours of work that would gain little benefit and likely many downsides and new problems. I don't think there is an appetite to move again anytime soon. 

As far as barrier of entry, I'd invite you play around with the site: it's different than Hugo, yes, but it's not so different that anyone with Hugo experience won't be able to pick it up rapidly.

**Comment by danish-mehmood** [comment]
@stockholmux  makes sense now , thanks for the explanation.
