### ISSUE TITLE
Add command grouping

### ISSUE THREAD

**Issue by Yury-Fridlyand** [valkey-io/valkey-io.github.io#150]
**Is your feature request related to a problem? Please describe.**

There are almost 400 commands listed on one page. It is a kinda messy.

**Describe the solution you'd like**

Add command grouping with an easy way to switch between groups or switch to another command within a group.

**Describe alternatives you've considered**

mmm...website search?

**Additional context**

**Comment by stockholmux** [comment]
Agreed. I think we need an alpha _and_ command category list.

There is some odd complexity here in the data we inherited. The site sources data from the command JSON files and they have `group` field but they aren't exactly what you might think - e.g. there is a group called 'generic' which probably needs a better explanation.

I'm open to some other method of categorization as long as it's data-driven.
