### ISSUE TITLE
Fix resources/about content

### ISSUE THREAD

**Issue by madolson** [valkey-io/valkey-io.github.io#165]
On the footer of every page there is an "about" that links to some text which I don't think we ever really reviewed. It also says, "Connect with with Valkey" at the top. I think https://valkey.io/topics/history/ is a better primer, but probably should be cleaned up a bit since it's a little stale now.

**Comment by stockholmux** [comment]
Yeah, that predates the actual history file and was a _very_ early contribution (April 10).

**Comment by stockholmux** [comment]
Fixed by #167
