### ISSUE TITLE
[Bug] Add logo

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-io.github.io#28]
**Describe the bug**

Valkey has now has a logo! 

![valkey-logo-only](https://github.com/valkey-io/valkey-io.github.io/assets/1152927/a99acafe-5f0b-473a-b3ea-11021e07c7ef)

**Expected behavior**

The site should have a logo in the upper left hand corner in the header and should have favico set to the new logo. Ideally this would match the blue text color.

We should also [credit the logo creator](https://github.com/dizys) in the footer.

**Screenshots**

n/a

**Additional context**

n/a

**Comment by kris-ms** [comment]
Hi there, #63 will hopefully close this,

Sing out if there's any problems with the PR and I'll sort it out.

Cheers
