### ISSUE TITLE
[BUG] Typos on homepage 

### ISSUE THREAD

**Issue by stockholmux** [valkey-io/valkey-io.github.io#64]
**Describe the bug**

Two typos on the home page:

> Valkey is an open source (BSD) high-performance key/value datastore that supports a variety **of** workloads such as caching, message queues, and can act as a primary database.
> 
> You can operate on data structures in-place with **an** expressive collection of commands.

**Comment by kris-ms** [comment]
I've got some minutes available, I'll shoot through a quick PR to sort this out!

**Comment by madolson** [comment]
Resolved in https://github.com/valkey-io/valkey-io.github.io/pull/66
