### ISSUE TITLE
[NEW] Website | Docs?

### ISSUE THREAD

**Issue by ultimateshadsform** [valkey-io/valkey-io.github.io#7]
What should we create the website with or the docs with?

What technology should we use for the docs?

Should we use Vitepress for that or what do you all want to use?

Should we use Nuxt 3 for the frontend or what do you all want?

Just wondering.
I mean I know it's early and everything but it was just an idea.

Edit: Nvm I just was that it's already started.

**Comment by madolson** [comment]
You can find the temporary URL at https://d18m7x5q574jh8.cloudfront.net/ as well as on the main page. Once things are "mostly" working, we can update the url to point to this. 

W.r.t. hugo and other things. Our decision was that we would like to get the website working (so would rather continue with what we have), but be wiling to update and change in the future.

**Comment by zuiderkwast** [comment]
There are some special stuff like automatic links to the commands and some exception when using asyntax like `` `!PING` `` that makes it NOT link to the command with that name...

I would assume using the Hugo thing would work out of the box (almost) with links and content working.

Agree we don't want versioned docs. The history entry we have is enough and very good. I also wouldn't like long complex URLs. It's nice to be able to type an URL in the address bar like how you type in a terminal. So `https://valkey-io/commands/xreadgroup` etc. is my preference. Also aligning with existing links in the content in the doc repo is important. Let's not change for the sake of changing.

**Comment by zuiderkwast** [comment]
I like this logo, a hexagon labyrinth with the key in the middle.

**Comment by stockholmux** [comment]
@dizys You want to submit the colours you came up with as the official Valkey colour pallet? #55

**Comment by zuiderkwast** [comment]
@stockholmux Do you mean these? https://github.com/valkey-io/valkey/issues/82#issuecomment-2035079091

**Comment by dizys** [comment]
> @dizys You want to submit the colours you came up with as the official Valkey colour pallet? #55

To be clear, the color pallet used in https://github.com/valkey-io/valkey/issues/82#issuecomment-2035079091 is by @madolson I believe. 😊

**Comment by madolson** [comment]
Yes! I added the colors with the help of a graphic designer. Sorry if that wasn't clear.

**Comment by madolson** [comment]
This seems mostly closed at this point and seems pretty idle.
