### ISSUE TITLE
RSS feed for the blog

### ISSUE THREAD

**Issue by brainwo** [valkey-io/valkey-io.github.io#79]
**Is your feature request related to a problem? Please describe.**

There are currently no way to follow Valkey blog.

**Describe the solution you'd like**

Add RSS feed to the blog. Preferably RSS 2.0 with full article embedded in it.

**Additional context**

Discussed in https://github.com/orgs/valkey-io/discussions/575

<div type='discussions-op-text'>

<sup>Originally posted by **brainwo** May 30, 2024</sup>
Is there RSS for Valkey blog?</div>

**Comment by stockholmux** [comment]
Hey @brainwo - second request for that this week!

We're literally in the middle of switching site generators, but it looks like our [new generator has the capability](https://www.getzola.org/documentation/templates/feeds/).

**Comment by captainepoch** [comment]
I would also love to have this to add the RSS feed to my RSS reader.

**Comment by stockholmux** [comment]
closed by #86 https://valkey.io/atom.xml

**Comment by captainepoch** [comment]
Thanks!
